PUT http://localhost:3000/updatePassword/6218d61eb72257a7ae430f91 HTTP/1.1
Content-Type: application/json

{
    "previousPassword":"bushra12343",
    "newPassword":"bushra12341",
    "newConfirmPassword":"bushra12341"
}